# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryShop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column=b'Name', max_length=100)),
                ('Address', models.CharField(db_column=b'Address', max_length=100)),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
    ]
