# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryShop', '0005_auto_20161123_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(db_column=b'Price', null=True, verbose_name=b'\xd0\xa6\xd1\x96\xd0\xbd\xd0\xb0'),
        ),
    ]
