# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryShop', '0009_auto_20161128_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoldOut', models.BooleanField(db_column=b'SoldOut', default=False, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xb0\xd0\xbb\xd1\x96\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xbe')),
                ('ProductToShop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BakeryShop.ProductToShop')),
            ],
            options={
                'db_table': 'BarCode',
            },
        ),
    ]
