# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryShop', '0010_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtoshop',
            name='DateTime',
            field=models.DateTimeField(db_column=b'DateTime'),
        ),
    ]
