# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryShop', '0012_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionHasBarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OK', models.BooleanField(db_column=b'OK', default=False, verbose_name=b'\xd0\x9d\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xbd\xd0\xbe')),
                ('BarCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BakeryShop.BarCode')),
                ('Revision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BakeryShop.Revision')),
            ],
            options={
                'db_table': 'RevisionHasBarCode',
            },
        ),
    ]
