# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BakeryShop', '0013_revisionhasbarcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(db_column=b'DateTime')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Sale',
            },
        ),
        migrations.AddField(
            model_name='barcode',
            name='Sale_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BakeryShop.Sale'),
        ),
    ]
